### ISSUE TITLE
Inital Values and Naming

### ISSUE THREAD

**Issue by Soyvolon** [Soyvolon/img-crypt#17]
https://github.com/Soyvolon/img-crypt/blob/be1ef62b9ff098474860e58eb69d60fcf14579fc/src/Core/Data/Settings_Profile.py#L4
https://github.com/Soyvolon/img-crypt/blob/2f75d4845cb2977156b6ca356704d3053c133506/src/Core/Data/User_Profile.py#L4

Firstly - these should be UUIDs, not a random integer. Secondly, these should be initialized to a default value. Only the database/database manager should be editing the UUID for a settings object.
<hr />
Also - file names for class files should match the name of the class itself, namely, being in upper camel case.

Packages are apparently supposed to be lowercase, so I guess we should change all the folders to lowercase.
https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

**Comment by ChopstickLeg** [comment]
So, just assign the self.uuid to like 0 instead of a random integer?

**Comment by Soyvolon** [comment]
No, you need to use the UUID class in python:
https://docs.python.org/3/library/uuid.html

**Comment by Soyvolon** [comment]
Actually, just set it to `None`. The DB will handle the random generation of uuid values.
